export const USER_AUTHENTICATED = 'user_authenticated';
export const LOGOFF = 'logoff';

export const BATTERY_MODELS_RETRIEVED = 'BATTERY_MODELS_RETRIEVED';
export const BATTERY_MODEL_CREATED = 'BATTERY_MODEL_CREATED';
export const BATTERY_MODEL_UPDATED = 'BATTERY_MODEL_UPDATED';
export const BATTERY_MODEL_DELETED = 'BATTERY_MODEL_DELETED';

export const VEHICLE_CREATED = 'VEHICLE_CREATED';
export const VEHICLE_DELETED = 'VEHICLE_DELETED';
export const VEHICLES_RETRIEVED_FOR_BATTERY = 'VEHICLES_RETRIEVED_FOR_BATTERY';
export const VEHICLE_MODELS_RETRIEVED = 'VEHICLE_MODELS_RETRIEVED';
